### ISSUE TITLE
Does this work for BTC to LTC direclty ??

### ISSUE THREAD

**Issue by adeelotx** [litecoin-project/insight-lite-api#16]
I want to know that if there's any api that can send BTC >> LTC && vice versa conversion directly ??

**Comment by rromanchuk** [comment]
You would need a traditional order book, see https://docs.gdax.com/  

There is much more to be said on this topic, but I think you're going to need a stronger fundamental understanding of what you're actually asking before heading down that path. I see you're posting this question across various projects on github, stop doing that.
