### ISSUE TITLE
Change ticker to LTC

### ISSUE THREAD

**Issue by eabz** [litecoin-project/insight-lite-api#21]
Hello, 
I am working with a multicurrency wallet to be used for use your crypto on debit cards.
I am using HD wallets, but seems that the insight api is not correctly configurated, is just receiving btc as ticker, it will work if I was just using it, but I am using 6 or 7 apis.
So, anybody can work it to use ltc ticker, or should I create my own api.
I am using this website: https://insight.litecore.io/

**Comment by majestic84** [comment]
This library is for Litecoin, and https://insight.litecore.io does not return bitcoin data, it returns Litecoin data.

**Comment by eabz** [comment]
@majestic84 
Then why I am getting this response from wallet-service: 
`Error: Coin ltc not supported by this provider`

**Comment by majestic84** [comment]
Please post your code so we can take a look at your usage. I haven't personally used wallet-service, but should be able to help you figure it out.
