### ISSUE TITLE
Estimate Fee feature not working

### ISSUE THREAD

**Issue by adityataday** [litecoin-project/insight-lite-api#25]
Request: https://localhost:3001/insight-lite-api/utils/estimatefee[?nbBlocks=2]
Response: 
{
status: 404,
url: "/insight-lite-api/utils/estimatefee[?nbBlocks=2]",
error: "Not found"
}

**Comment by ultragtx** [comment]
Works here: https://insight.litecore.io/api/utils/estimatefee?nbBlocks=2

**Comment by adityataday** [comment]
ok, will look into it. Thanks
