### ISSUE TITLE
List blocks api `/blocks` not working

### ISSUE THREAD

**Issue by anhgien** [litecoin-project/insight-lite-api#4]
Hi guys,
The list blocks api `/blocks` doesn't work, I inspect source code and realized `Bitcore` has `getBlockHashesByTimestamp` method and this method call `getblockhashes`.
I tested litecoin-cli commands (litecoin 0.13.2) with method `getblockhashes` (method returns an array of block hashes for a specified block range, ex: two timestamps) but it return `Method not found`, is it removed?
If it was removed, so is there a method that has the same feature with above method?

**Comment by ultragtx** [comment]
Hi @anhgien 
litecore does not use the original [litecoin](https://github.com/litecoin-project/litecoin), instead it uses a modified version [litecore-litecoin](https://github.com/litecoin-project/litecore-litecoin) which added extra indexes and functions including `getblockhashes`.

**Comment by anhgien** [comment]
thanks, it worked
