### ISSUE TITLE
localhost:3001/insight-api giving a 404

### ISSUE THREAD

**Issue by ltyu** [litecoin-project/insight-lite-api#6]
None of the routes are working such as /insight-api/tx/

I'm running node v4.8.4

**Comment by losh11** [comment]
Still having this issue?

**Comment by ltyu** [comment]
Nope, its been resolve. Thanks!

**Comment by plwalters** [comment]
If anyone finds this issue in the future this is because the url should be `/insight-lite-api/tx/` (note the lite in there, if `insight-lite` is working it means you installed the bitcore service)
